### ISSUE TITLE
May I know what reconstruction algorithm are you using?

### ISSUE THREAD

**Issue by Shawn207** [HKUST-Aerial-Robotics/FC-Planner#1]
Could you provide a resource of the reconstruction algorithm you chose? Did you run it real-time on the drone or off-line after flight?
Thanks!

**Comment by Chen-Albert-FENG** [comment]
Thank you for your interest in our work!  Actually, due to the edge computation platform on the drone, we chose to reconstruct the 3D model from the collected images after the coverage flight using commercial software, Reality Capture.
