### ISSUE TITLE
Questions about mesh and point cloud

### ISSUE THREAD

**Issue by EnqiBaiCN2000** [HKUST-Aerial-Robotics/FC-Planner#11]
您好，我想在自己的场景中使用Fc-planner，请问源文件中每个场景（mbs，Christ和pipe）中的点云数据和mesh数据都分别用什么软件生成的呢，以及在我使用自己的场景时有哪些需要注意的（例如：输入点云数据有且只有表面点云）感谢您的指导。

**Comment by Chen-Albert-FENG** [comment]
感谢您对我们工作的关注！
首先其实只需要一个表面的mesh 因为可以利用pcl_tool将mesh采样成点云 对于输入一定要是表面的mesh及其采样得到的点云即可
其次mesh的话我们都是从现有的互联网数据中获取的 而非生成的

**Comment by Chen-Albert-FENG** [comment]
@EnqiBaiCN2000 您好，请问您已经解决这个问题了吗？
