### ISSUE TITLE
ERROR:Normal Estimation...

### ISSUE THREAD

**Issue by LJX981213** [HKUST-Aerial-Robotics/FC-Planner#12]
Hello，the following error message occurred when running on my data
[ERROR] Normal Estimation.
[ERROR] Final downsample voxel size: 0.020000, cloud size:1530

**Comment by LJX981213** [comment]
![17266498902129](https://github.com/user-attachments/assets/6f7cfa55-72c4-4de5-9fd9-869330785608)

**Comment by Chen-Albert-FENG** [comment]
Hi! This line does not mean a real error in this process but just gives the outputs in the terminal in the red since I use the print command via "ROS_ERROR()".
