### ISSUE TITLE
运行 hcplanner_exec 程序时遇到了一个断言错误，导致程序异常终止（图片中标明了错误提示）

### ISSUE THREAD

**Issue by Li-source-gif** [HKUST-Aerial-Robotics/FC-Planner#13]
运行 hcplanner_exec 程序时遇到了一个断言错误，导致程序异常终止
![微信图片_20240923192759](https://github.com/user-attachments/assets/ee31550c-f7c1-4018-be1c-04eda3a942fd)

**Comment by Chen-Albert-FENG** [comment]
您好 您可以看到trace到的信息时初始化时TrajGenerator的构造函数在预分配内存时出现了问题 并且和eigen有关 除此之外没有看到过多信息 之前并没有遇到这样的错误 请问这种情况是稳定复现吗？

**Comment by Li-source-gif** [comment]
是的老师，是按照您的那个项目的说明书一步一步复现的。也可以正常的编译，但是到运行的时候就出现了上述错误，具体执行的操作命令就是图片里面的这个
![%N)0D4PF _304482)ADQ8FW](https://github.com/user-attachments/assets/e9a43235-fd83-477b-9ac1-e0ec51a44044)

**Comment by Li-source-gif** [comment]
我在执行这个命令的时候出现了之前图片里面提到的遇到了一个断言错误，导致程序异常终止。

**Comment by Chen-Albert-FENG** [comment]
我之前没有遇到这样的error因为这并不是运行过程中的报错而是在初始化时候出现了内存预分配的问题 如果可以您可否试试其他设备上会不会出现这样的问题？

**Comment by Li-source-gif** [comment]
冯老师，是不是换一台电脑设备，这个问题就可能不会再出现了

**Comment by Li-source-gif** [comment]
陈老师，您的意思是更换其他的电脑设备，这个问题就可能就不会出现了是吗

**Comment by Li-source-gif** [comment]
冯老师，您的意思是如果更换电脑设备，可能这个问题就不会出现了是吗？

**Comment by Chen-Albert-FENG** [comment]
@Li-source-gif 我不确定，因为我之前没有遇到这个问题，我在如果你更换了其他设备试试还会不会有这样的问题来排除掉这个error，因为这个报错并不是代码内部的运行报错

**Comment by Li-source-gif** [comment]
冯老师，在quick start 部分的两条指令（图片所示），需要把zsh改成bash才能执行，这个是为什么呢，我后面的那个报错是不是因为这里的原因呢？您在执行的是时候进行修改了吗？比如下面的这个：原文：source devel/setup.zsh && roslaunch hierarchical_coverage_planner rviz.launch需要改为source devel/setup.bash && roslaunch hierarchical_coverage_planner rviz.launch

**Comment by Li-source-gif** [comment]
冯老师，在quick start 部分的两条指令（图片所示），需要把zsh改成bash才能执行，这个是为什么呢，我后面的那个报错是不是因为这里的原因呢？您在执行的是时候进行修改了吗？比如下面的这个：原文：source devel/setup.zsh && roslaunch hierarchical_coverage_planner rviz.launch需要改为source devel/setup.bash && roslaunch hierarchical_coverage_planner rviz.launch
![1727180012035](https://github.com/user-attachments/assets/3eda3e70-e05c-48f0-b190-8370ace678a8)

**Comment by Chen-Albert-FENG** [comment]
@Li-source-gif bash和zsh取决于你的系统使用的什么shell，ubuntu默认是bash而我使用的zsh，这个up to 每个人系统的shell设定。这应该没有影响的。

**Comment by ZhongFuJing** [comment]
楼主您好，请问这个问题解决了吗？
