### ISSUE TITLE
Viewpoint_manager for indoor environment

### ISSUE THREAD

**Issue by ruomingzhai** [HKUST-Aerial-Robotics/FC-Planner#15]
Hi, really appreciate your extraordinary work.
I have some problem when runing the plugin package of viewpoint_manager. There is a note saying "Important notice: this package only supports surface point cloud, which means interior should be clear."
But the 2.5D map illustrated is containing interior walls, which also runs successfully in my device.
When I run my own point clouds with both walls and furnitures, all the furnitures are missing in the rviz map. I hope get some clues from you and make it consider these furnitures while generating viewpoints.

**Comment by Chen-Albert-FENG** [comment]
Sorry for the late reply. Actually, the surface point cloud means the objectives that we want the robot to see. For 2.5D map, we firstly use an exploration framework get the surface points then we use these points as input to viewpoint_manager pkg. As for your case, could you obtain the surface of the map not the interior by some operations? Afterwards, you can use these surface points as input to use our viewpoint_manager pkg.

**Comment by ruomingzhai** [comment]
Thanks for your replying. I annotated the following codes in  the inputModel() function:
void inputModel()
{
    pcl::PointCloud<pcl::PointXYZ>::Ptr tmp_model;
    double factor = 1.75;
    tmp_model.reset(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::io::loadPCDFile<pcl::PointXYZ>(model_path_, *tmp_model);
    for (int i = 0; i < (int)tmp_model->points.size(); i++)
    {
        tmp_model->points[i].x *= factor;
        tmp_model->points[i].y *= factor;
        tmp_model->points[i].z *= 1.4;
        // if (tmp_model->points[i].z < 0.55)
        //     continue;
        model_->points.push_back(tmp_model->points[i]);
    }

And all point clouds can be visualized but the generated viewpoints seem focus on the walls and leave out other furnitures.
![snap](https://github.com/user-attachments/assets/e1695c58-b00a-45bc-918a-34e493d7ad1e)
I want all the point cloud to be considered in generation progress. Hope get some clues from

**Comment by Zager-Zhang** [comment]
The `viewpoint_manager_node.cpp` in `viewpoint_manager` is just an example implemented on a 2.5D map. It simply generates initial viewpoints based on normal vectors for 2.5D map usage. In practical applications, I recommend you generate sufficient (covering all walls and furniture) and safe initial viewpoints, and then use the `updateViewpoints()` function of `viewpoint_manager` to update and obtain high-quality viewpoints.

**Comment by Zager-Zhang** [comment]
Of course, it's also possible that some parameters, like the viewpoint distance, aren't properly configured, leading to the filtering out of many unsafe initial viewpoints. You might want to look into that as well.

**Comment by Chen-Albert-FENG** [comment]
BTW, I noticed your map is actually a 3D case e.g., table plane, you can try treating it without yaw=0 constraint. Parameters are vital such as visible distance and sample distance, which should fit your case.
