### ISSUE TITLE
您好，配置仿真环境的时候，是否必须安装Anaconda？

### ISSUE THREAD

**Issue by Li-source-gif** [HKUST-Aerial-Robotics/FC-Planner#16]
![87()PJX35H}KJ)~356N_J)I](https://github.com/user-attachments/assets/8359f008-4cf9-464f-a320-5e2f04d4707a)

**Comment by Chen-Albert-FENG** [comment]
您好，不是必须安装anaconda，如果您安装了可以使用这行命令来指定编译时的python。
