### ISSUE TITLE
能否利用机械臂进行工件检测路径规划

### ISSUE THREAD

**Issue by zct-cap** [HKUST-Aerial-Robotics/FC-Planner#17]
您好，看了你们的成果，想请问下这个项目可以支持用于机械臂携带摄像头对复杂曲面工件检测时的路径规划吗？工件尺寸较小

**Comment by Chen-Albert-FENG** [comment]
您好，理论上是支持的，但是请注意我们生成的轨迹其实是对应于机械臂末端执行器的轨迹，如果想要转化为机械臂各关节执行信号，可能需要逆运动学解算，以及需要添加机械臂本身的feasibility和safety约束。
