### ISSUE TITLE
能否用于机械臂小物体检测

### ISSUE THREAD

**Issue by hjh-2001** [HKUST-Aerial-Robotics/FC-Planner#18]
嫩否通过修改尺寸等用于机械臂检测工件

**Comment by Chen-Albert-FENG** [comment]
您好，理论上是支持的，但是请注意我们生成的轨迹其实是对应于机械臂末端执行器的轨迹，如果想要转化为机械臂各关节执行信号，可能需要逆运动学解算，以及需要添加机械臂本身的feasibility和safety约束。

**Comment by hjh-2001** [comment]
谢谢您的回答
