### ISSUE TITLE
REQUIRED process [rosa_exec-2] has died!

### ISSUE THREAD

**Issue by yxwang99** [HKUST-Aerial-Robotics/FC-Planner#2]
My compilation process went well, but when I ran redbird.launch I had following problem.

[ INFO] [1713882490.040349904]: [SSD] Initialized!
[ERROR] [1713882490.051120913]: Normal Estimation...
[ERROR] [1713882490.073935301]: Final downsample voxel size: 0.022000, Cloud size: 1702
[ INFO] [1713882490.074012178]: [SSD] normalize time = 23.128171 ms
[ INFO] [1713882490.105747681]: [SSD] calculate adj matrix time = 27.445752 ms.
[ INFO] [1713882490.232477864]: [SSD] drosa estimation time = 126.697679 ms.
[ INFO] [1713882490.244523691]: [SSD] dcrosa estimation time = 11.964825 ms.
[ INFO] [1713882490.245141611]: [SSD] line extraction time = 0.602194 ms.
[ INFO] [1713882490.245294499]: [SSD] recentering time = 0.140780 ms.
[ INFO] [1713882490.245313783]: [SSD] graph decomposition time = 0.009794 ms.
[ INFO] [1713882490.245334278]: [SSD] inner decomposition time = 0.010102 ms.
2_element_Merge_id:1
similarity:36.0729
[ WARN] [1713882490.245362855]: Without Merging Intermediate Branch...
branch_merge->segments: 23
branch_merge->pairs: 5
[ INFO] [1713882490.245381078]: [SSD] branch merge time = 0.036611 ms.
{11 12 13 14 15 }
{11 2 }
{2 3 4 5 6 7 8 9 10 17 18 19 20 21 22 23 }
{11 1 16 }
{11 0 }
[ INFO] [1713882490.245405462]: [SSD] restore scale time = 0.009717 ms.
[ INFO] [1713882490.280546280]: [SSD] distribute original cloud time = 35.126361 ms.
[ INFO] [1713882490.280921255]: [SSD] calculate inner dist time = 0.181904 ms.
[ INFO] [1713882490.280945014]: [SSD] store real graph time = 0.003847 ms.
[ INFO] [1713882490.280952613]: [SSD] SSD latency = 206.912763 ms. Normal estimation costs 23.157958 ms.
[ INFO] [1713882490.280961367]: [SSD] --- <SSD finished> --- 
================================================================================REQUIRED process [rosa_exec-2] has died!

My enviorment: ceres 2.2.0,   eigen 3.3.9,    pcl-1.14.0

**Comment by Chen-Albert-FENG** [comment]
Hi! I did not know what happened. I guess some visualization errors. Thus, I tested the code on my machine and it worked. I have updated the code. Could you try it again?

**Comment by Chen-Albert-FENG** [comment]
So sry :( I found one uninitialized variable and tested on different machines, where some crashed. Thus, I guess it resulted in errors. I have fixed it and updated the code. Could you test the code when you feel free?

**Comment by yxwang99** [comment]
The code runs well. Thanks for your sharing, it's really helpful~
