### ISSUE TITLE
城市建筑骨架提取有问题

### ISSUE THREAD

**Issue by Haonan-DONG** [HKUST-Aerial-Robotics/FC-Planner#22]
感谢您的工作及开源，我对您的工作十分感兴趣，并且利用城市数据尝试了下，总体是能跑通的，但遇到了一些问题，我通过无人机图像数据三维重建首先得到的mesh，再重采样得到点云，算法中输入该点云：
1. rosa提取骨架的时候，骨架点总是提取半空中，而非全部在点云内部
2. 因为（1）的原因（推测），规划出来的路径会进入点云内部

请问是否是因为算法参数的问题呢？
期待您的回复

文末附上效果图：p1为原始点云，p2为骨架点，p3为rosa点，异常点以蓝色边框标出
![p1](https://github.com/user-attachments/assets/d6934ed2-b1da-47b5-92c3-842c8444696c)
![p2](https://github.com/user-attachments/assets/f27de99d-b393-402a-bcbb-6e2789646767)
![p3](https://github.com/user-attachments/assets/d41a0781-0cec-40e1-99fc-026ffae81546)

原始点云数据为：
链接：https://pan.baidu.com/s/1zDrx1Zwsa0uXWGdgDDAb8g?pwd=ycaz 
提取码：ycaz

**Comment by Chen-Albert-FENG** [comment]
您好，很感谢您关注我们的工作，目前FC-Planner v1版本比较依赖于骨架提取的超参数，目前这套参数比较适用于“细长”结构，您可能需要调整参数以达到比较好的效果，btw，您可以关注我们后续的工作 v2版本，将实现parameter-free，谢谢。

**Comment by Haonan-DONG** [comment]
感谢回复，祝顺利
