### ISSUE TITLE
 Plans for Porting FUEL Planner to ROS 2?

### ISSUE THREAD

**Issue by zeeshanns** [HKUST-Aerial-Robotics/FC-Planner#23]
Hi,

Are there any plans to port the FUEL planner to ROS 2? With ROS 2 becoming the standard for robotics, a ROS 2 version would greatly enhance its usability.
if not then, Could you provide any guidance or insights into challenges I might face?

**Comment by Chen-Albert-FENG** [comment]
Hi, actually, I'm not the author of FUEL planner. You can find help from https://github.com/HKUST-Aerial-Robotics/FUEL.
