### ISSUE TITLE
ubuntu18.04 catkin_make error

### ISSUE THREAD

**Issue by EnqiBaiCN2000** [HKUST-Aerial-Robotics/FC-Planner#6]
I have encountered such a compilation error. How can I solve it? Thank you for your guidance！ 

fatal error: quadrotor_msgs/PolynomialTraj.h: 没有那个文件或目录
 #include <quadrotor_msgs/PolynomialTraj.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
![2024-05-15 11-29-44 的屏幕截图](https://github.com/HKUST-Aerial-Robotics/FC-Planner/assets/104008012/f1049904-5030-488f-8b7f-3071d788a68b)

**Comment by Chen-Albert-FENG** [comment]
Hi! Actually, I have not countered this error but I see your folder format is "/YOUR_MACHINE/workspace/src/FC-Planner", then you compile the project under "/YOUR_MACHINE/workspace"? In the installation step at README, you just clone this project like "/YOUR_MACHINE/workspace/FC-Planner" and "cd FC-Planner & catkin_make". Afterwards, you may see "build" and "devel" under "/YOUR_MACHINE/workspace/FC-Planner". Could you try it again when you feel free?

**Comment by Chen-Albert-FENG** [comment]
Hi! We have updated the compilation steps. Have you tried it?
