### ISSUE TITLE
question about running on my own dataset

### ISSUE THREAD

**Issue by tangyubbb** [HKUST-Aerial-Robotics/FC-Planner#7]
我知道对于每一个场景都要准备一个pcd 模型和一个mesh模型，请问这个pcd模型和mesh模型都是用什么获取的？
pcd使用Lidar slam的方法重建吗？
mesh我看你说是用的reality capture，请问这个Mesh模型有尺度恢复吗？
你们的pcd模型和Mesh是在一个尺度下面吗？
.dae文件也是用RC软件生成吗？
是不是pcd模型主要用于骨架提取，mesh主要用于全覆盖路径规划的覆盖率计算，我正在通过你们的代码试图了解这一点。

**Comment by Chen-Albert-FENG** [comment]
您好，感谢您关注我们的工作！

对于输入数据来说您如果只有一个mesh模型就可以直接使用 因为mesh可以通过pcl tools直接转成任意密度的pcd 之后的所有计算都是接受pcd作为输入 但您的mesh需要只有表面信息内部不能用面片 因为我们只支持表面点云

如果您想使用lidar slam获取到的点云的话 您可以直接在input mesh那里随意放置一个参数即可 如上文所讲并不会影响计算 只是可视化时候把mesh关掉就好了

对于评估覆盖率 我们会采用密度更大的点云来保证信息的完整度从而充分评估是否做到了完整覆盖 当然这里的点云也可以通过mesh转化 （如果没有mesh可以直接用你输入的点云）

“为什么要用RC？” 如果您提供了mesh我们是可以根据mesh和算法生成的全覆盖路径渲染出一系列图片直接拿来做photogrammetry得到三维重建的结果 定性直观地展现我们的确收集到了充分完整的信息 当然如果您没有提供mesh那么这一步可以省略

总结：只需要表面点云即可算出全覆盖路径 这个点云既可以是mesh转过来的 也可以是收集得到的 但必须是表面点云

**Comment by tangyubbb** [comment]
非常感谢您的快速回复，帮助我进行下一步测试，祝工作学习顺利&nbsp;


742951391
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 中午12:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HKUST-Aerial-Robotics/FC-Planner] question about running on my own dataset (Issue #7)














 
您好，感谢您关注我们的工作！
 
对于输入数据来说您如果只有一个mesh模型就可以直接使用 因为mesh可以通过pcl tools直接转成任意密度的pcd 之后的所有计算都是接受pcd作为输入 但您的mesh需要只有表面信息内部不能用面片 因为我们只支持表面点云
 
如果您想使用lidar slam获取到的点云的话 您可以直接在input mesh那里随意放置一个参数即可 如上文所讲并不会影响计算 只是可视化时候把mesh关掉就好了
 
对于评估覆盖率 我们会采用密度更大的点云来保证信息的完整度从而充分评估是否做到了完整覆盖 当然这里的点云也可以通过mesh转化 （如果没有mesh可以直接用你输入的点云）
 
“为什么要用RC？” 如果您提供了mesh我们是可以根据mesh和算法生成的全覆盖路径渲染出一系列图片直接拿来做photogrammetry得到三维重建的结果 定性直观地展现我们的确收集到了充分完整的信息 当然如果您没有提供mesh那么这一步可以省略
 
总结：只需要表面点云即可算出全覆盖路径 这个点云既可以是mesh转过来的 也可以是收集得到的 但必须是表面点云
