### ISSUE TITLE
Does it support ROS2?

### ISSUE THREAD

**Issue by lida2003** [HKUST-Aerial-Robotics/FC-Planner#8]
NVIDIA Jetson Orin Platform JetPack 6.0 doesn't ROS1 anymore.

so does it support ROS2, or what kind of changes need to be made, any plan for upgrade?

PS: ROS 1 support is deprecated and will be removed in a future release, just from Ubuntu 22.04(jammy).

**Comment by Chen-Albert-FENG** [comment]
Thank you for your interest on our work! Until now, we only support ROS1 but we will try our best to transfer the code based on ROS2 in the future.

**Comment by lida2003** [comment]
@Chen-Albert-FENG Is there any plan for the code transfer or porting schedule ?

**Comment by Chen-Albert-FENG** [comment]
I cannot give you the actual plan or timeline in the current stage but this engineering effort will not be finished in the near months...

**Comment by lida2003** [comment]
Thanks for the info. Hope to see it in the near future!
